### ISSUE TITLE
请问这个播放器考虑开源吗

### ISSUE THREAD

**Issue by jerrydeng-tkg** [solstice23/mimi-radio#1]
这个播放器考虑开源吗，提供更换本地音频与歌词，让我们更加方便的更换音频吗

**Comment by solstice23** [comment]
https://github.com/solstice23/mimi-radio/tree/main/src

**Comment by jerrydeng-tkg** [comment]
请问shorts.json 和songs.json 是什么 歌曲文件是存放在？
